// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OvStats_Website.DBContext;

#nullable disable

namespace OvStats_Website.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OvStats_Website.DTO.SummonerAccountDTO", b =>
                {
                    b.Property<string>("accountId")
                        .HasColumnType("text");

                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("profileIconId")
                        .HasColumnType("integer");

                    b.Property<string>("puuid")
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .HasColumnType("text");

                    b.Property<long>("revisionDate")
                        .HasColumnType("bigint");

                    b.Property<long>("summonerLevel")
                        .HasColumnType("bigint");

                    b.HasKey("accountId");

                    b.ToTable("SummonerAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
